import { useRef } from 'react'
import { X, Download, CheckCircle } from 'lucide-react'
import { formatDateTime, formatDate } from '../utils/dateUtils'

/**
 * TransactionReceiptModal Component
 * Displays transaction receipt after successful transfer/transaction
 * Features:
 * - Shows transaction details in local timezone
 * - Save as PDF using browser print dialog
 * - Close button and backdrop click to dismiss
 */
const TransactionReceiptModal = ({ receipt, onClose }) => {
  const receiptRef = useRef(null)

  if (!receipt) return null

  const formatAmount = (amount) => {
    return Math.abs(Number(amount)).toLocaleString('en-US', {
      minimumFractionDigits: 2,
      maximumFractionDigits: 2
    })
  }

  const handleSavePDF = () => {
    // Use browser print to save as PDF
    const printContent = receiptRef.current.innerHTML
    const printWindow = window.open('', '_blank')
    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>Receipt - ${receipt.id}</title>
          <style>
            * { box-sizing: border-box; margin: 0; padding: 0; }
            body {
              font-family: Arial, sans-serif;
              background: #fff;
              color: #000;
              padding: 2rem;
            }
            .receipt-header { text-align: center; margin-bottom: 1.5rem; padding-bottom: 1rem; border-bottom: 2px solid #FF6B00; }
            .bank-name { color: #FF6B00; font-size: 1.8rem; font-weight: 800; }
            .bank-sub { color: #FF6B00; font-size: 0.9rem; font-weight: 700; letter-spacing: 0.1em; }
            .receipt-title { color: #333; font-size: 1rem; margin-top: 0.5rem; }
            .status-badge { display: inline-block; background: #e6fff0; border: 1px solid #4dff88; color: #00a651; padding: 4px 16px; border-radius: 100px; font-size: 0.85rem; font-weight: 700; text-transform: uppercase; margin-top: 0.75rem; }
            .amount-box { background: #fff5ee; border: 1px solid #FF6B00; border-radius: 12px; padding: 1.5rem; text-align: center; margin: 1.5rem 0; }
            .amount-label { color: #888; font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.08em; }
            .amount-value { color: #FF6B00; font-size: 2rem; font-weight: 800; margin-top: 0.25rem; }
            .detail-row { display: flex; justify-content: space-between; padding: 0.75rem 0; border-bottom: 1px solid #eee; }
            .detail-label { color: #888; font-size: 0.875rem; }
            .detail-value { color: #000; font-size: 0.875rem; font-weight: 600; text-align: right; max-width: 60%; }
            .footer { text-align: center; margin-top: 1.5rem; padding-top: 1rem; border-top: 1px solid #eee; color: #aaa; font-size: 0.75rem; }
            .logo { width: 60px; height: 60px; object-fit: contain; margin-bottom: 0.5rem; }
            .success-icon { color: #00a651; font-size: 2rem; margin-bottom: 0.5rem; }
          </style>
        </head>
        <body>
          <div class="receipt-header">
            <img 
              src="${window.location.origin}/orange-logo.jpg" 
              class="logo" 
              alt="O-rangeankus Logo"
              onerror="this.style.display='none'"
            />
            <div class="bank-name">O-rangeankus</div>
            <div class="bank-sub">BANK&TRUST</div>
            <div class="receipt-title">Transaction Receipt</div>
            <div class="status-badge">✓ ${receipt.status || 'COMPLETED'}</div>
          </div>

          <div class="amount-box">
            <div class="amount-label">Transaction Amount</div>
            <div class="amount-value">$${formatAmount(receipt.amount)}</div>
          </div>

          ${[
            ['Transaction ID', `#${receipt.id}`],
            ['Reference', receipt.reference || 'N/A'],
            ['Type', receipt.type || 'Transfer'],
            ['From', receipt.sender || 'N/A'],
            ['To', receipt.recipient || 'N/A'],
            ['Description', receipt.description || 'N/A'],
            ['Transaction Date', formatDateTime(receipt.posting_date || receipt.created_at)],
          ].map(([label, value]) => `
            <div class="detail-row">
              <span class="detail-label">${label}</span>
              <span class="detail-value">${value}</span>
            </div>
          `).join('')}

          <div class="footer">
            <p>This receipt was generated by O-rangeankus Bank&Trust</p>
            <p>Generated on ${formatDateTime(new Date().toISOString())}</p>
            <p>Thank you for banking with us</p>
          </div>
        </body>
      </html>
    `)
    printWindow.document.close()
    printWindow.focus()
    setTimeout(() => {
      printWindow.print()
      printWindow.close()
    }, 500)
  }

  return (
    // Backdrop
    <div
      onClick={onClose}
      style={{
        position: 'fixed',
        top: 0, left: 0, right: 0, bottom: 0,
        background: 'rgba(0,0,0,0.8)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 9999,
        padding: '1rem'
      }}
    >
      <div
        ref={receiptRef}
        onClick={e => e.stopPropagation()}
        style={{
          background: '#1A1A1A',
          border: '1px solid rgba(255,107,0,0.25)',
          borderRadius: '20px',
          padding: '2rem',
          width: '100%',
          maxWidth: '480px',
          maxHeight: '90vh',
          overflowY: 'auto',
          position: 'relative',
          animation: 'slideUp 0.3s ease'
        }}
      >
        {/* Close Button */}
        <button
          onClick={onClose}
          style={{
            position: 'absolute',
            top: '1rem', right: '1rem',
            background: 'rgba(255,255,255,0.06)',
            border: '1px solid rgba(255,255,255,0.1)',
            borderRadius: '50%',
            width: '32px', height: '32px',
            color: '#fff', cursor: 'pointer',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            padding: 0
          }}
        >
          <X size={16} />
        </button>

        {/* Success Icon */}
        <div style={{ textAlign: 'center', marginBottom: '1.25rem' }}>
          <div style={{
            width: '64px', height: '64px',
            background: 'rgba(77,255,136,0.1)',
            border: '2px solid rgba(77,255,136,0.3)',
            borderRadius: '50%',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            margin: '0 auto 1rem'
          }}>
            <CheckCircle size={32} color="#4dff88" />
          </div>

          {/* Logo */}
          <img
            src="/orange-logo.jpg"
            alt="O-rangeankus"
            style={{
              width: '48px', height: '48px',
              objectFit: 'contain', borderRadius: '50%',
              marginBottom: '0.5rem'
            }}
            onError={(e) => e.target.style.display = 'none'}
          />

          <h2 style={{
            color: '#FF6B00', fontWeight: 800,
            fontSize: '1.4rem', margin: 0
          }}>
            O-rangeankus
          </h2>
          <p style={{
            color: '#FF6B00', fontSize: '0.7rem',
            fontWeight: 700, letterSpacing: '0.1em',
            textTransform: 'uppercase', opacity: 0.8,
            margin: '2px 0 6px'
          }}>
            Bank&Trust
          </p>
          <p style={{ color: '#888', fontSize: '0.85rem' }}>
            Transaction Receipt
          </p>

          {/* Status */}
          <div style={{
            display: 'inline-block', marginTop: '0.75rem',
            padding: '4px 16px',
            background: 'rgba(77,255,136,0.1)',
            border: '1px solid rgba(77,255,136,0.3)',
            borderRadius: '100px', color: '#4dff88',
            fontSize: '0.8rem', fontWeight: 700,
            textTransform: 'uppercase', letterSpacing: '0.05em'
          }}>
            ✓ {receipt.status || 'Completed'}
          </div>
        </div>

        {/* Amount Box */}
        <div style={{
          background: 'rgba(255,107,0,0.06)',
          border: '1px solid rgba(255,107,0,0.2)',
          borderRadius: '12px', padding: '1.25rem',
          textAlign: 'center', marginBottom: '1.5rem'
        }}>
          <p style={{ color: '#888', fontSize: '0.75rem', textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: '0.4rem' }}>
            Transaction Amount
          </p>
          <p style={{ color: '#FF6B00', fontSize: '2rem', fontWeight: 800, margin: 0 }}>
            ${formatAmount(receipt.amount)}
          </p>

          {/* Show fee if present */}
          {receipt.fee && (
            <>
              <div style={{ borderTop: '1px solid rgba(255,255,255,0.1)', margin: '0.75rem 0' }} />
              <div style={{
                display: 'flex', justifyContent: 'space-between',
                alignItems: 'center', marginTop: '0.75rem'
              }}>
                <span style={{ color: '#888', fontSize: '0.85rem' }}>Transaction Fee</span>
                <span style={{ color: '#FF6B00', fontWeight: 700 }}>
                  -${formatAmount(receipt.fee)}
                </span>
              </div>
              <div style={{
                display: 'flex', justifyContent: 'space-between',
                alignItems: 'center', marginTop: '0.5rem',
                paddingTop: '0.75rem',
                borderTop: '1px solid rgba(255,255,255,0.1)'
              }}>
                <span style={{ color: '#fff', fontSize: '0.9rem', fontWeight: 700 }}>Total Deducted</span>
                <span style={{ color: '#FF6B00', fontSize: '1.1rem', fontWeight: 800 }}>
                  ${formatAmount(parseFloat(receipt.amount) + parseFloat(receipt.fee))}
                </span>
              </div>
            </>
          )}
        </div>

        {/* Details */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '0' }}>
          {[
            ['Transaction ID', `#${receipt.id}`],
            ['Reference', receipt.reference || 'N/A'],
            ['Type', receipt.type || 'Transfer'],
            ['From', receipt.sender || 'N/A'],
            ['To', receipt.recipient || 'N/A'],
            ['Description', receipt.description || 'N/A'],
            ['Transaction Date', formatDateTime(receipt.posting_date || receipt.created_at)],
          ].map(([label, value]) => (
            <div key={label} style={{
              display: 'flex', justifyContent: 'space-between',
              alignItems: 'flex-start', gap: '1rem',
              padding: '0.75rem 0',
              borderBottom: '1px solid rgba(255,255,255,0.05)'
            }}>
              <span style={{ color: '#888', fontSize: '0.85rem', flexShrink: 0 }}>
                {label}
              </span>
              <span style={{
                color: '#fff', fontSize: '0.85rem',
                fontWeight: 600, textAlign: 'right',
                wordBreak: 'break-word', maxWidth: '60%'
              }}>
                {value}
              </span>
            </div>
          ))}
        </div>

        {/* Footer */}
        <p style={{
          textAlign: 'center', color: '#555',
          fontSize: '0.75rem', margin: '1.25rem 0'
        }}>
          Thank you for banking with O-rangeankus Bank&Trust
        </p>

        {/* Action Buttons */}
        <div style={{ display: 'flex', gap: '0.75rem' }}>
          <button
            onClick={onClose}
            style={{
              flex: 1, padding: '12px',
              background: 'rgba(255,255,255,0.05)',
              border: '1px solid rgba(255,255,255,0.1)',
              borderRadius: '10px', color: '#fff',
              fontWeight: 600, cursor: 'pointer',
              fontSize: '0.9rem',
              transition: 'background-color 0.2s'
            }}
            onMouseOver={e => e.currentTarget.style.background = 'rgba(255,255,255,0.08)'}
            onMouseOut={e => e.currentTarget.style.background = 'rgba(255,255,255,0.05)'}
          >
            Close
          </button>
          <button
            onClick={handleSavePDF}
            style={{
              flex: 1, padding: '12px',
              background: '#FF6B00', border: 'none',
              borderRadius: '10px', color: '#fff',
              fontWeight: 700, cursor: 'pointer',
              fontSize: '0.9rem',
              display: 'flex', alignItems: 'center',
              justifyContent: 'center', gap: '6px',
              transition: 'background-color 0.2s'
            }}
            onMouseOver={e => e.currentTarget.style.background = '#E55A00'}
            onMouseOut={e => e.currentTarget.style.background = '#FF6B00'}
          >
            <Download size={16} /> Save as PDF
          </button>
        </div>
      </div>

      <style>{`
        @keyframes slideUp {
          from { opacity: 0; transform: translateY(30px); }
          to { opacity: 1; transform: translateY(0); }
        }
      `}</style>
    </div>
  )
}

export default TransactionReceiptModal
